project:
  type: book
  output-dir: docs


book:
  title: "Machine Learning Foundations: A Comprehensive Guide from Python to Mathematics"
  author: "Mr. Saeed Ullah"
  date: "20/01/2024"
  favicon: images/icon.png
  page-navigation: true



  chapters:
    - index.qmd
    - about author.qmd
    - setup.qmd
    - part: Python Programming Basics
      restart-chapter-numbering: true
      chapters: 
        - python basics.qmd
        - flow control.qmd
        - functions.qmd
        - lists.qmd
        - dictionaries.qmd
        - string manipulation.qmd
    - part: Automation with Python
      restart-chapter-numbering: true
      chapters:
        - pattern matching with regex.qmd
        - input validation.qmd
        - Reading and writing files.qmd


bibliography: references.bib


format:
  html:
    theme:
      light: flatly
      dark: darkly    

  pdf:
    documentclass: scrreprt
    header-includes:
      - \makeatletter
      - \@addtoreset{chapter}{part}
      - \makeatother           

